### ISSUE TITLE
Implementation of shortlisted libraries

### ISSUE THREAD

**Issue by aasmithadhani** [SimPPL/arbiter-project-tracking#27]
- We conducted thorough research to compare various visualization libraries, including d3, Plotly, Chart.js, ECharts, and google charts.
- The main goal was to find the best-suited library for our project, considering factors like features, performance, and compatibility. 
- We utilized the profiler functionality in Next.js to assess the duration taken for both the mounting and updating processes.
-  Furthermore, we standardized the comparative analysis by incorporating bar graphs and pie charts for each library, thereby enhancing the visual representation of performance metrics across the board. This approach allowed for a comprehensive and easily interpretable evaluation of the libraries under consideration.
- More information regarding the libraries and the time taken can be found at the below given document:-
- https://docs.google.com/document/d/1IZPfeGu9JKnQ9nH6oVibnjk44qai34-Dks0ecVT4Qcw/edit?usp=sharing

**Comment by SwapneelM** [comment]
Can you confirm whether there is a link to the shortlisted libraries? Issues should be clear and self-complete and not need the reader to search for anything else. You are free to link wherever you want to link things but please be complete in listing out issues otherwise I cannot follow any of the ongoing work.

Second, can you link to where you have analyzed the library's execution and discussed efficiency so that I can follow along the docs and code implementation please?

**Comment by SwapneelM** [comment]
<img width="1469" alt="Screenshot 2024-02-08 at 11 48 55 AM" src="https://github.com/SimPPL/arbiter-project-tracking/assets/13250132/ba79b652-8b7a-469d-85c8-ca583b767eaf">

Here is an example for what an issue should be looking like.
